### ISSUE TITLE
sndml3 

### ISSUE THREAD

**Issue by mjocasio** [gflewis/sndml3#11]
I ran the process for an oracle sink........ I used last two template jar for Oracle sndml3.0.3 and 02 and did not 
      map correctly or pull out any data....... I wondering which is the best wait to debug this problem.

**Comment by gflewis** [comment]
Best way to debug is to create a script that replicates a very small amount of data (e.g. 1 row) and use a Log4J2 config that dumps out everything.  See: https://github.com/gflewis/sndml3/wiki/Log4j2

**Comment by mjocasio** [comment]
Thanks for the input.... I have another question.... I was able to move the data from Servicenow to MySql and PostGreSql...... Im trying to do the same to MSSQL
The url for MSSQL is the following :  jdbc:sqlserver://xxxxxxx.com:1433

so the connection is success but it tries to create a table in the master database.and I get a permission error.. is there a way you could pass the database name such as you do in Oracle , Post and MySql.

url:  jdbc:mysql://yyyyyyyy:3306/mySQLData

url: jdbc:oracle:@zzzzzzzzzzzzzzzz:1521:orcl

url:jdbc:postgresql://wwwwwww:5432/postData

these last two connect and writes successfully to their respective repository.

Any ideas


________________________________

**Comment by gflewis** [comment]
You can specify "databaseName" in the MS SQLServer URL. Please see: https://github.com/gflewis/sndml3/issues/7

**Comment by mjocasio** [comment]
Thanks it did work like a charm...... the parameter was quite different than the other url databases...

Now the Oracle one.... It connects successfully to AWS RDS Oracle but it does not retrieves nothing back....
this is the configuration setting I used

datamart.url=jdbc:oracle:thin:@oracledb.xxxxxxx.us-xxx-1.rds.amazonaws.com:1521:orcl



________________________________

**Comment by gflewis** [comment]
@mjocasio - Your RDS Oracle URL looks verify similar to mine. I am not sure why you would be having trouble. Can you please confirm whether you are still having difficulty with Oracle, and let me know which jar file you are using. Thanks.

**Comment by gflewis** [comment]
Please feel free to open a new issue if you are still having difficulties.

**Comment by mjocasio** [comment]
All problems were solved... when reserve words from Oracle are use in a query I need it to put the word in enclose in quotes...... so when I try to do a select statement I thought I was getting nulls values back.

thank you

**Comment by mjocasio** [comment]
We are moving forward implementing your dialect version SNDML3 for Oracle database. Can you recommend an java environment so we could clone and recompile the dependencies of the application for security purpose? Second, our long term goal will be to move to SAP HANA as the database destination. At the present time, your project does not provide a template for this repository. This is a another reason we will like to clone the current SNDML3 so we could try to revise and implement this database. Any suggestion are welcome.

thanks

**Comment by gflewis** [comment]
I normally run on AWS Linux with OpenJDK 1.7.  For development I will use
JavaSE 1.7 or 1.8.  You should not have any Java issues if you are using
1.7 or higher.

I have not used SAP HANA, so I will be interested to hear how you make out.
Sometimes for a new JDBC driver you can get by with modifying
sqltemplates.xml, but if the database is non-standard you may need to patch
the code in the servicenow.datamart package.  Usually this is in
DatabaseStatement.bindField() or the Generator class or in
ColumnDefinitions which reads the database schema. Be sure to enable
assertions when testing.

Best of luck.

**Comment by mjocasio** [comment]
Im having two issues that I can't pass thru when I build the package.... It does not create a jar for Oracle or MS SQL Server. Although, when I first test it, it warn me of the dependencies missing. So I download and execute mvn install for both the sqljdbc41.jar and ojdbc7.jar. The revision segment of the pom that applies for the scope for test and compile looks like see below and everything else was left alone including the package phase....
Just dont know what I need to change to trigger this portion of the build phase to be execute it. It does build for mySQL, Pg and the generic one.... Any inputs will be appreciate.

 <dependency>
      
      <groupId>com.microsoft.sqlserver</groupId>
      <artifactId>sqljdbc</artifactId>
      <version>4.1</version>
      <scope>test</scope>
      <optional>true</optional>
    </dependency>
    <dependency>
      
      <groupId>com.oracle</groupId>
      <artifactId>ojdbc8</artifactId>
      <version>12.2.0.1</version>
      <scope>test</scope>
      <optional>true</optional>
    </dependency>
  </dependencies>

________________________________

**Comment by gflewis** [comment]
Try
mvn package -Pgithub.release

**Comment by mjocasio** [comment]
thank you so much..... moving on

________________________________

**Comment by mjocasio** [comment]
Just to make sure I understand correctly...... The schema sets this configuration setting at run time..... No need to do anything in the SNOW instance but it will impact when landing the data at the database.


All date and timestamp processing is done in UTC. Dates and timestamps are stored in UTC in the SQL database. If you need to display dates and/or times using other time zones, you should set a database variable and allow the database client to do the translation. For MySQL, use the following to convert to US/Eastern

set time_zone = 'US/Eastern';


 Pages 16


thanks

**Comment by gflewis** [comment]
You should make sure the ServiceNow user account that you are using has their timezone set to GMT.

For some databases, such as PostgreSQL, you need to make sure the JVM timezone is GMT. But I think for Oracle it does not matter because there is an "alter session set time_zone" command in the sqltemplates.xml file.

**Comment by mjocasio** [comment]
Hope your doing ok... we are moving on implementing the Data Mart Load in our system to transfer data from SNOW to Oracle.
While testing and loading the first sets of tables, we found the prune or sync operations to reflect records deleted in the target table didn't work as expected. I notice on your blog discussion , somebody pointed out the same problem a while ago.

I was wondering if there is a revision for this or should I have to go in the code a make necessary changes.

thanks
