### ISSUE TITLE
Connecting to SQL Server

### ISSUE THREAD

**Issue by ChuckHowie1** [gflewis/sndml3#19]
Getting error:
Exception in thread "main" servicenow.datamart.ResourceException: java.sql.SQLException: No suitable driver found for jdbc:mssql://servername.com/SNOW

running this from command line:
C:\sndml3-master\sndml-3.1.2-bin\sndml-3.1.2>java -jar sndml-3.1.2-mssql.jar -p Profile.txt -t cmn_location

Profile is:
servicenow.instance=https://company.service-now.com
servicenow.username=snowacct
servicenow.password=snowpwd
datamart.url=jdbc:mssql://10.10.10.10;SNOW
datamart.username=SNOW_Admin
datamart.password=helloWorld
Any help much appreciated...
I have tried changing the sql server to the fqdn, as well as including the port..ie jdbc:mssql://servername.com:1433/SNOW
and get the same error...i've tried semicolon then dbname ie 1433;SNOW ...same error

**Comment by gflewis** [comment]
For datamart.url, try
jdbc:sqlserver://<hostname>

Here is a reference:
https://docs.microsoft.com/en-us/sql/connect/jdbc/building-the-connection-url?view=sql-server-ver15
