### ISSUE TITLE
sndml3 support for SQLite Database/Datasource

### ISSUE THREAD

**Issue by samik-shah** [gflewis/sndml3#26]
Is sndml3 API supports SQLite Database/Datasource? if Yes, then what is the procedure to install sndml3 on windows platform to communicate with SQLite database?

**Comment by gflewis** [comment]
There is no pre-built JAR file for SQLite. In addition, the **templates.xml** file needs to be modified because SQLite croaks on the GRANT command which is in the default template.

I am running on a Mac, not Windows, but I was able to get this to work using the MySQL JAR with a few tweaks. You will need the following files in the same directory as your SQLite database.

- **sndml-3.2.0-mysql.jar**
- **sqltemplates.xml** - You can pull this from github. It is in the src/main/resources directory
- SQLite JDBC JAR file - I used **sqlite-jdbc-3.8.11.2.jar** because I happened to have it sitting around, but a more recent version should work fine.

The first step is to modify **sqltemplates.xml**. Change line 52 to 

    <grant></grant>

In other words, remove the GRANT command from the default profile.

Next you will need a connection profile. Mine looked like this:

    servicenow.instance=dev****** 
    servicenow.username=********
    servicenow.password=********
    datamart.url=jdbc:sqlite:sndm.db
    datamart.schema=main
    datamart.templates=sqltemplates.xml

In your Java command you will need to specify both JAR files. I ran the following command, and was able to load the sys_user table, but it may be a bit different on Windows.
 
    java -cp sndml-3.2.0-mysql.jar:sqlite-jdbc-3.8.11.2.jar servicenow.datamart.Loader -p sndml.profile -t sys_user

Let me know if  you were able to get this procedure to work.  I can probably build support for SQLite into the next release, but it will be several weeks.

**Comment by samik-shah** [comment]
> There is no pre-built JAR file for SQLite. In addition, the **templates.xml** file needs to be modified because SQLite croaks on the GRANT command which is in the default template.
> 
> I am running on a Mac, not Windows, but I was able to get this to work using the MySQL JAR with a few tweaks. You will need the following files in the same directory as your SQLite database.
> 
> * **sndml-3.2.0-mysql.jar**
> * **sqltemplates.xml** - You can pull this from github. It is in the src/main/resources directory
> * SQLite JDBC JAR file - I used **sqlite-jdbc-3.8.11.2.jar** because I happened to have it sitting around, but a more recent version should work fine.
> 
> The first step is to modify **sqltemplates.xml**. Change line 52 to
> 
> ```
> <grant></grant>
> ```
> 
> In other words, remove the GRANT command from the default profile.
> 
> Next you will need a connection profile. Mine looked like this:
> 
> ```
> servicenow.instance=dev****** 
> servicenow.username=********
> servicenow.password=********
> datamart.url=jdbc:sqlite:sndm.db
> datamart.schema=main
> datamart.templates=sqltemplates.xml
> ```
> 
> In your Java command you will need to specify both JAR files. I ran the following command, and was able to load the sys_user table, but it may be a bit different on Windows.
> 
> ```
> java -cp sndml-3.2.0-mysql.jar:sqlite-jdbc-3.8.11.2.jar servicenow.datamart.Loader -p sndml.profile -t sys_user
> ```
> 
> Let me know if you are able to get this procedure to work. I can probably build support for SQLite into the next release, but it will be several weeks.

Thank You for your quick response, I will try and let you know about whether I get the success in it or not.

**Comment by samik-shah** [comment]
> There is no pre-built JAR file for SQLite. In addition, the **templates.xml** file needs to be modified because SQLite croaks on the GRANT command which is in the default template.
> 
> I am running on a Mac, not Windows, but I was able to get this to work using the MySQL JAR with a few tweaks. You will need the following files in the same directory as your SQLite database.
> 
> * **sndml-3.2.0-mysql.jar**
> * **sqltemplates.xml** - You can pull this from github. It is in the src/main/resources directory
> * SQLite JDBC JAR file - I used **sqlite-jdbc-3.8.11.2.jar** because I happened to have it sitting around, but a more recent version should work fine.
> 
> The first step is to modify **sqltemplates.xml**. Change line 52 to
> 
> ```
> <grant></grant>
> ```
> 
> In other words, remove the GRANT command from the default profile.
> 
> Next you will need a connection profile. Mine looked like this:
> 
> ```
> servicenow.instance=dev****** 
> servicenow.username=********
> servicenow.password=********
> datamart.url=jdbc:sqlite:sndm.db
> datamart.schema=main
> datamart.templates=sqltemplates.xml
> ```
> 
> In your Java command you will need to specify both JAR files. I ran the following command, and was able to load the sys_user table, but it may be a bit different on Windows.
> 
> ```
> java -cp sndml-3.2.0-mysql.jar:sqlite-jdbc-3.8.11.2.jar servicenow.datamart.Loader -p sndml.profile -t sys_user
> ```
> 
> Let me know if you are able to get this procedure to work. I can probably build support for SQLite into the next release, but it will be several weeks.
![Authorization_Error_While_Accessing_sys_dictionary_through_given_java_command](https://user-images.githubusercontent.com/79859716/109698594-92f8ad80-7bb5-11eb-8212-3ed8509477d4.jpg)

- I have setup all the required jars and path environment variable with all 3 required jars, and able to connect with Servicenow, but encountered Authorization error while accessing sys_dictionary of servicenow through java command as provided by you. I have attached the screenshot of the same for your reference.
![Authorization_Error_While_Accessing_sys_dictionary_through_given_java_command](https://user-images.githubusercontent.com/79859716/109698521-81170a80-7bb5-11eb-8891-2bcae36ba567.jpg)

**Comment by gflewis** [comment]
This is a ServiceNow security error. Please refer to this page:
https://github.com/gflewis/sndml3/wiki/Non-Admin

**Comment by gflewis** [comment]
Please let me know if this issue can be closed.

**Comment by samik-shah** [comment]
Thank You for the help !

I could able to fetch different tables' content of ServiceNow CMDB into SQLite database successfully by using java command as specified by you.

I have one more query, that is - if I want to capture only 9 to 10 columns' data of 'sys_user' table instead of all 86 columns, then how to do that?

**Comment by gflewis** [comment]
Either drop the columns that you do not want from your SQLite table, or rebuild the SQLite table with only the columns you want. These columns are mandatory: sys_id, sys_created_on, sys_updated_on. All other columns are optional. The primary key is always sys_id. If the table already exists, then SNDML will not rebuild the table or add columns.

**Comment by samik-shah** [comment]
Is it possible that at the time of executing the following command itself, can we decide which columns of sys_user table of SNOW CMDB we want? 
**something like:
java -cp sndml-3.2.0-mysql.jar:sqlite-jdbc-3.8.11.2.jar servicenow.datamart.Loader -p sndml.profile -t sys_user <column_name_1> <column_name_2> <column_name_3> <column_name_4>**

As I couldn't get it how to rebuild the SQLite table, can you suggest me in which way can we rebuild the table in SQLite database with only desired columns without dropping the unwanted columns, I mean if I want exactly 7 to 8 columns of 'sys_user' table into SQLite DB Table from the very start, is it any method to rebuild table with mandatory 3 columns plus other 4 to 5 columns, **or can we write the JAVA command to fetch only desired column as I mentioned above?**

Thank You for Your Support and Co-Operation on this.

**Comment by gflewis** [comment]
There is a **columns** option described on this wiki page, but it only affects the loading of data, not table creation:

https://github.com/gflewis/sndml3/wiki/Table-Settings

In version 3.4 (when it becomes available) the **columns** setting will affect table creation.

For now you need to create the table manually. For example, if you wanted three columns -- user_name, name, email -- then you would use these SQLite commands:

    drop table sys_user;
    create table sys_user(sys_id not null primary key, sys_created_on, sys_updated_on, user_name, name, email);

Please refer to the Metrics wiki page for instructions on processing newly added or updated records.

https://github.com/gflewis/sndml3/wiki/Metrics
