### ISSUE TITLE
Config validation fails when there is a number in the source table name

### ISSUE THREAD

**Issue by ecg0030** [gflewis/sndml3#34]
It seems that sources with digits ([0-9]) aren't allowed:

```
if (!Pattern.compile("[a-z_]+").matcher(source).matches())
		configError("Invalid source: " + source);
```

https://github.com/gflewis/sndml3/blob/1d6405399cfcb00e84f03d33ee757caed13fba0a/src/main/java/sndml/datamart/JobConfig.java#L225

I couldn't see a workaround for this, is there a reason this isn't supported?

**Comment by gflewis** [comment]
Looks like a bug. I have patched the code in v3.4.6. Let me know if this fixes it for you.
