### ISSUE TITLE
DatabaseInsertWriter Process: Failed/Skipped

### ISSUE THREAD

**Issue by jonathangull** [gflewis/sndml3#35]
While copying a large table , getting these warning messages , does these mean the records are not mirrored? I checked few and it looked like they are replicated. Can you please advise.

1:35:21 WARN DatabaseInsertWriter [DPRUN0001001] DPRUN0001001 PROCESS: Failed/Skipped 6dbec543872f3010a7eac9570cbbxx35b4
01:35:21 WARN DatabaseInsertWriter [DPRUN0001001] DPRUN0001001 PROCESS: Failed/Skipped 6dbf392487570d5x0a7eac9570cbb35d4
01:35:21 WARN DatabaseInsertWriter [DPRUN0001001] DPRUN0001001 PROCESS: Failed/Skipped 6dc086dd68705c11019f110e83cbb35fe
01:35:21 WARN DatabaseInsertWriter [DPRUN0001001] DPRUN0001001 PROCESS: Failed/Skipped 6dc09381877141101d9f110e83cbb35f1
01:35:21 WARN DatabaseInsertWriter [DPRUN0001001] DPRUN0001001 PROCESS: Failed/Skipped 6dc16eb9871e0d10bd1ad32e80cbb3579
01:35:21 WARN DatabaseInsertWriter [DPRUN0001001] DPRUN0001001 PROCESS: Failed/Skipped 6dc1b8a787dbc1d0a7eac9570dcbb35dc
01:35:21 WARN DatabaseInsertWriter [DPRUN0001001] DPRUN0001001 PROCESS: Failed/Skipped 6dc22e64872389d0a7eac957a0cbb35e3
01:35:21 WARN DatabaseInsertWriter [DPRUN0001001] DPRUN0001001 PROCESS: Failed/Skipped 6dc4c3c88753c550a7eac9570cabb35d0
01:35:21 WARN DatabaseInsertWriter [DPRUN0001001] DPRUN0001001 PROCESS: Failed/Skipped 6dc4fe9a87777c10bd1d32e80cbxb3576
01:35:21 WARN DatabaseInsertWriter [DPRUN0001001] DPRUN0001001 PROCESS: Failed/Skipped 6dc52ae8872389da0a7eac9570cbb35c9

**Comment by jonathangull** [comment]
one observation is, all records (175k) seem to be mirrored ,but log keeps spitting these warnings along with messages like this ..

02:19:45 INFO RestTableReader [DPRUN0001001] DPRUN0001001 PROCESS: Processed 7000 / 162773

**Comment by gflewis** [comment]
This warning will occur if you are using the INSERT action, but the record already exists in the target table. INSERT will not overwrite an existing record. If you want to overwrite existing records then use UPSERT/UPDATE action instead of INSERT.
