### ISSUE TITLE
NullPointerException for sync action using partition and created filter returns no records

### ISSUE THREAD

**Issue by kilo323** [gflewis/sndml3#4]
When using a configuration for sync and combining a created filter and there are not any results returned from ServiceNow, a null pointer is thrown as started and finished metrics are not being set.

*Note that update works fine and sync works if you remove the partition option.*

**Example config item**

threads: 1
metrics: C:/temp/all_tables.metric
tables:
- {source: cmn_cost_center, target: sndml_cmn_cost_center, action: sync, partition: week, created: today}

**Error Stack Trace**
Exception in thread "main" java.lang.NullPointerException
	at servicenow.api.WriterMetrics.getElapsedSec(WriterMetrics.java:46)
	at servicenow.api.WriterMetrics.write(WriterMetrics.java:128)
	at servicenow.datamart.Loader.writeAllMetrics(Loader.java:109)
	at servicenow.datamart.Loader.loadTables(Loader.java:101)
	at servicenow.datamart.Loader.main(Loader.java:61)

**Log Entries**
12:25:40 INFO [main] LoaderConfig GLOBAL INIT: 
threads: 1
metrics: C:/temp/all_tables.metric
tables:
- {source: cmn_cost_center, target: sndml_cmn_cost_center, action: sync, partition: week,
  created: today}
12:25:48 WARN [main] RestTableAPI cmn_cost_center PROCESS: getStats query="sys_created_on>=2018-06-29^sys_created_on<2018-06-29 17:25:40" minCreated=null maxCreated=null
12:25:48 INFO [main] RestTableAPI cmn_cost_center PROCESS: getStats count=0 query="sys_created_on>=2018-06-29^sys_created_on<2018-06-29 17:25:40" createdRange=[null,null]
12:25:48 INFO [main] LoaderJob sndml_cmn_cost_center INIT: partition=null
12:25:48 INFO [main] LoaderJob sndml_cmn_cost_center INIT: begin sync sndml_cmn_cost_center (0 rows)
12:25:48 INFO [main] LoaderJob cmn_cost_center FINISH: end load sndml_cmn_cost_center (0 rows)
12:25:48 INFO [main] Loader GLOBAL FINISH: Writing C:\temp\all_tables.metric
Exception in thread "main" java.lang.NullPointerException
	at servicenow.api.WriterMetrics.getElapsedSec(WriterMetrics.java:46)
	at servicenow.api.WriterMetrics.write(WriterMetrics.java:128)
	at servicenow.datamart.Loader.writeAllMetrics(Loader.java:109)
	at servicenow.datamart.Loader.loadTables(Loader.java:101)
	at servicenow.datamart.Loader.main(Loader.java:61)

**Comment by gflewis** [comment]
Confirmed as a reproducible bug in 3.0.2. Workarounds as identified are (a) use action "update" instead of "sync" or (2) remove the partition.

Will try to fix in 3.0.3. Thanks for identifying this.

**Comment by kilo323** [comment]
Thanks!  Not really an issue for me, it just so happened that while I was getting this setup I was using a created range to not pull much data.  My normal process for sync will not fail but figured I would pass along this finding to you.

Nice program by the way, thanks for putting this together!

**Comment by gflewis** [comment]
Fixed in 3.0.3
