### ISSUE TITLE
ERROR AgentScanner [scanner] main ERROR: sndml.datamart.ConfigParseException: Unrecognized field "status"

### ISSUE THREAD

**Issue by justinHat** [gflewis/sndml3#53]
I originally installed the Datapump v.1.1 update set and successfully exported data to our sql server instance.

After installing the Datapump v3.5.0 Upgrade.xml and creating/executing a new job, the sndml-3.4.6-mssql.jar daemon returns the following error messages:

10:05:27 ERROR AgentScanner [scanner] main ERROR: run: sndml.datamart.ConfigParseException
10:05:27 ERROR AgentScanner [scanner] main ERROR: sndml.datamart.ConfigParseException: Unrecognized field "status" (class sndml.datamart.JobConfig), not marked as ignorable (24 known properties: "start", "truncate", "created", "number", "partition", "minRows", "sys_id", "sql", "drop", "pageSize", "target", "last", "filter", "since", "source", "maxRows", "doc_id", "threads", "autoCreate", "sqlBefore", "sqlAfter", "action", "columns", "name"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: sndml.datamart.JobConfig["status"])
sndml.datamart.ConfigParseException: Unrecognized field "status" (class sndml.datamart.JobConfig), not marked as ignorable (24 known properties: "start", "truncate", "created", "number", "partition", "minRows", "sys_id", "sql", "drop", "pageSize", "target", "last", "filter", "since", "source", "maxRows", "doc_id", "threads", "autoCreate", "sqlBefore", "sqlAfter", "action", "columns", "name"])
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: sndml.datamart.JobConfig["status"])
        at sndml.datamart.ConfigFactory.jobConfig(ConfigFactory.java:108) ~[sndml-3.4.6-mssql.jar:?]
        at sndml.daemon.AgentScanner.getJobList(AgentScanner.java:133) ~[sndml-3.4.6-mssql.jar:?]
        at sndml.daemon.MultiThreadScanner.scan(MultiThreadScanner.java:54) ~[sndml-3.4.6-mssql.jar:?]
        at sndml.daemon.AgentScanner.run(AgentScanner.java:64) [sndml-3.4.6-mssql.jar:?]
        at java.util.TimerThread.mainLoop(Timer.java:566) [?:?]
        at java.util.TimerThread.run(Timer.java:516) [?:?]
10:05:27 ERROR AgentDaemon [scanner] main FINISH: Aborting the daemon

Is anyone familiar with these exceptions and do you have any advice on a resolution?

Thanks,
Justin

**Comment by gflewis** [comment]
Hi Justin.

sndml-3.4.6-mssql.jar is not compatible with Update Set "Datapump v3.5.0 Upgrade.xml". Can you try the following

1. JAR file: sndml-3.5.0-beta-3-mssql.jar
2. Update Set: DataPump 2024-08-17 Export.xml.

This Update Set is a full export of the application. I expect it to install cleanly on top of your existing app.  However, please let me know if it you get preview errors, or have issues after the installation.

There are a huge number of changes in 3.5 and I am still working on the documentation. 
Please keep me advised.
Thanks,
Giles

**Comment by gflewis** [comment]
P.s. You should be able to download the files here:
https://github.com/gflewis/sndml3/releases/tag/v3.5.0-beta-3

**Comment by gflewis** [comment]
Hi Justin.
If you have not upgraded already, then please upgrade to 3.5.0.05. 
Please open a new ticket if you get any preview errors with the "v3.5.0.05-Upgrade" Update Set attached to this release, or if you have any issues with 3.5.0.05.
Thanks,
Giles
- https://github.com/gflewis/sndml3/releases/tag/v3.5.0.05
