### ISSUE TITLE
 Load task with monthly partition : PROCESS: Failed/Skipped 

### ISSUE THREAD

**Issue by nlejeune** [gflewis/sndml3#8]
Hi,

I load the task table.

My YAML look like that: 

```
metrics: task.metrics
tables: 
- name: task
  created: [2015-10-01, 2018-08-31]
  truncate: true
  partition : month
```
when I execute, it create the table and start to load but a lot of record are skipped : 

> 03:09:37 INFO [main] DatabaseInsertWriter task.M2018-08-01 PROCESS: Failed/Skipped bca068eedbc867c04ac4302f9d961919
> 03:09:37 INFO [main] DatabaseInsertWriter task.M2018-08-01 PROCESS: Failed/Skipped f4a068eedbc867c04ac4302f9d96190b
> 03:09:37 INFO [main] DatabaseInsertWriter task.M2018-08-01 PROCESS: Failed/Skipped f8a068eedbc867c04ac4302f9d961992
> 03:09:37 INFO [main] DatabaseInsertWriter task.M2018-08-01 PROCESS: Failed/Skipped a1a0e8eedbc867c04ac4302f9d961914
> 03:09:37 INFO [main] DatabaseInsertWriter task.M2018-08-01 PROCESS: Failed/Skipped b1a068e2db886b40dde43a4d7c9619cb
> 03:09:37 INFO [main] DatabaseInsertWriter task.M2018-08-01 PROCESS: Failed/Skipped d6a0e8eedbc867c04ac4302f9d9619ea
> 03:09:37 INFO [main] DatabaseInsertWriter task.M2018-08-01 PROCESS: Failed/Skipped cba02ceedbc867c04ac4302f9d961991
> 03:09:37 INFO [main] DatabaseInsertWriter task.M2018-08-01 PROCESS: Failed/Skipped dfa02ceedbc867c04ac4302f9d9619cd
> 03:09:37 INFO [main] DatabaseInsertWriter task.M2018-08-01 PROCESS: Failed/Skipped dfa02ceedbc867c04ac4302f9d9619e4
> 03:09:37 INFO [main] DatabaseInsertWriter task.M2018-08-01 PROCESS: Failed/Skipped b7a06ceedbc867c04ac4302f9d96199f
> 03:09:37 INFO [main] DatabaseInsertWriter task.M2018-08-01 PROCESS: Failed/Skipped 14b0e8e2db886b40dde43a4d7c961978
> 03:09:39 INFO [main] DatabaseInsertWriter task.M2018-08-01 PROCESS: loaded 13874 / 16405 (13874 / 303391)

What does that mean ?

**Comment by gflewis** [comment]
"Failed/Skipped" means that you got an SQLIntegrityConstraintViolationException. Normally this means that there was a Primary Key violation on the insert. The primary key is sys_id. When you set "truncate: true" it switches the action to "insert".  (Without the truncate the default action is "update". If you set "action: update" then you will not get this error.)

Ordinarily it should be impossible to get a primary key violation on an insert following a truncate. Unless there is something else happening in the database. Is it possible you were also loading records from another window? It could also mean that some other process was changing the sys_created_on values in the background while the load was running. But that would be pretty weird.

**Comment by gflewis** [comment]
Here is another possibility: Are task records being deleted in the background? This could mess up the pagination (maybe) and cause it to process the same record twice. Or, is there a background process that is inserting records in the partition being processed?

**Comment by nlejeune** [comment]
Nothing was running in background and it was an initial load. Weird...

**Comment by gflewis** [comment]
A couple of things. Can you check the order_by clause, which should appear in the logs. In the beta version we were sometimes having trouble with PK violations on loads of large tables; but I thought we had fixed that with the order_by.

Are you having trouble with multiple partitions? Or only with the most recent partition? If is is the later, you might try reloading that date range with a smaller partition, e.g. "partition: day".

You also might try "action: sync" to find and fix the records that did not load the first time.

**Comment by gflewis** [comment]
Can you confirm that you are seeing something in the log that looks like this?
query="sys_created_on>=2018-08-01^sys_created_on<2018-08-31^ORDERBYsys_created_on^ORDERBYsys_id"

**Comment by nlejeune** [comment]
I will give another try tomorrow.
I flush the table and restart the load without the truncate parameter and it work well for now.

**Comment by gflewis** [comment]
I would like to close this issue. Please advise if you are still having trouble. Thanks.

**Comment by nlejeune** [comment]
Without the truncated option it worked.
